// Trail Maintenance — all player-visible strings. Swap this file to localize.
export const STR = {
  title: "TRAIL MAINTENANCE",
  subtitle: "PARK SERVICE WORK ORDER 6-114",
  begin: "BEGIN SHIFT",
  controlsDesktop: "WASD — move · MOUSE — look · E — interact · F — flashlight · click to lock mouse",
  hintFlashlight: "Press F for flashlight",
  controlsTouch: "LEFT SIDE — move · RIGHT SIDE — look · buttons — interact / light",
  clickToLook: "Click to look around",
  loading: "REWINDING TAPE…",
  paused: "PAUSED — click to resume",

  objClear: "OBJECTIVE: Clear storm damage on Trail 6",
  objShed: "OBJECTIVE: Check the maintenance shed",
  objOutpost: "OBJECTIVE: Report to the ranger outpost",
  objErase: "OBJECTIVE: Collect the loose markers",
  objCollect: "OBJECTIVE: Collect the loose markers",
  objClearing: "OBJECTIVE: Inspect the cabins",
  objLost: "OBJECTIVE: Get back to the car",
  objReturn: "OBJECTIVE: Return to the trailhead",

  taskBranches: "Clear fallen branches",
  taskMarkers: "Repaint trail markers",
  taskShedSign: "Inspect the posted notice",
  taskMap: "Check the wall map",
  taskRadio: "Check the radio",
  taskErase: "Collect markers",
  taskCollect: "Collect loose markers",
  taskInspect: "Inspect the cabins",

  pBranch: "[E] Clear branch",
  pPaint: "[E] Repaint marker",
  pErase: "[E] Erase marker",
  pCollect: "[E] Pick up marker",
  pInspect: "[E] Inspect cabin",
  pRead: "[E] Read",
  pRadio: "[E] Check radio",
  pTakeMap: "[E] Take park map",
  toastMapTaken: "Park map acquired — follow it",
  close: "[E] Put down",

  signTrailhead: "TRAIL 6 — CLOSED FOR MAINTENANCE\nSTORM DAMAGE AHEAD\nAUTHORIZED PERSONNEL ONLY",
  signParking: "TRAILHEAD PARKING\nTRAIL 6 ACCESS →\nPACK IN · PACK OUT",
  noteParking: "TRAILHEAD PARKING — DAY USE ONLY\n\nYour vehicle is the only one here.\nThe lot is empty. The gate at the road was open.\n\nTrail 6 begins at the treeline ahead.",
  signTrailheadChanged: "TRAIL 6 — OPEN\nALL VISITORS WELCOME\nSTAY ON THE MARKED PATH",
  signScenic: "SCENIC LOOP — 1.2 MILES",
  noteShed: "POSTED — DISTRICT OFFICE\n\nTRAIL CLOSED.\nDO NOT RESTORE.\n\nDamage is not the reason.\nLeave the markers faded.\nLet the brush take the line.\n\n— R. ALDEN, MAINT. SUPERVISOR",
  noteWallMap: "PARK TRAIL SYSTEM — SECTOR 4\n\nTRAILS 5, 6, 9: WITHDRAWN.\n\nDO NOT RESTORE OLD CONNECTORS.\n\nIf a route is repainted in error,\nremove every blaze the same night.\nDo not leave a continuous line\nbetween the markers and the gate.",
  noteDesk: "...keeps coming back to the same thing. The paint\nis the problem, not the path. A blaze isn't a sign,\nit's a signature. Markers give the trail permission.\n\nWe stopped painting in March. It stopped moving\nin April. Nobody writes this in the log.",
  noteMissing: "NOTICE BOARD — TRAIL ADVISORIES\n\n[ corner of a torn page ]\n[ corner of a torn page ]\n[ a rectangle of unfaded wood\n  where Trail 6's notice hung ]",
  noteRadioDead: "The handset is cold. The battery\ncompartment is empty. The cord\nis wrapped neatly, like someone\nclosed up and meant it.",

  radioContinue: "…CONTINUE RESTORATION…",
  radioConfirmed: "…RESTORATION CONFIRMED…",
  radioGarbled: "…[unintelligible]…",
  radioConcerned1: "…where are you. Where ARE you—",
  radioConcerned2: "…why are you out there. Nobody sent—  come back to the road. Now.",

  cabinNote1: "The door isn't locked — there's no door. The frame\nstands but the hinges rusted through years ago.\nInside: a stove furred with rust, a cot, a calendar.\nThe calendar's last page is decades old.",
  cabinNote2: "Dust lies even and thick on everything, undisturbed.\nA child's boot by the cold hearth, cracked stiff.\nNothing here has been touched in a very long time.\nNothing here was abandoned in a hurry.",
  cabinNote3: "Ledgers on a shelf, swollen with damp. One is open.\nThe last legible line: \"closed the connectors, took\nup the blazes, sealed the way.\" The ink stops there.\nThe pages after it were torn out.",
  cabinNote4: "This one's roof has fallen in. Saplings grow through\nthe floorboards — thin trees, decades old. Whatever\nlived here, the forest took back its ground long ago.\n\nBehind you, something moves between the trunks.",

  toastBranchesDone: "Storm damage cleared.",
  toastMarkersDone: "Markers repainted.",
  toastRedFound: "These were knocked loose. Better collect them.",
  toastClearing: "The trail ends at a clearing. Cabins.",
  toastLost: "The path you came in on is gone.",
  toastSilence: "The forest has gone quiet.",
  toastRepaint: "Something repainted a marker behind you.",

  endGoodTitle: "UNMARKED",
  endGoodText: "The park forgot the way.",
  endBadTitle: "PUBLIC ACCESS",
  endBadText: "Trail restored.",
  endLostTitle: "OFF TRAIL",
  endLostText: "The way in was the only way out.\nThey kept calling. You kept not answering.",
  endRestart: "WORK ANOTHER SHIFT",

  counterErase: (n, total) => `Red markers remaining: ${n} / ${total}`,
  counterDawn: "Dawn is coming.",
};
